# Generated by Django 6.0.5 on 2026-05-21 20:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('agency', models.CharField(default=1002, max_length=4)),
                ('number', models.CharField(max_length=7)),
                ('account_type', models.CharField(choices=[('CC', 'conta corrente'), ('CP', 'conta poupança')], default='CC', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
