# Generated by Django 6.0.5 on 2026-05-22 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_accountmodel_balance_alter_accountmodel_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
