# Generated by Django 6.0.5 on 2026-05-25 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientmodel',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='clientmodel',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='clientmodel',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='clientmodel',
            name='user_permissions',
        ),
    ]
