# Generated by Django 6.0.5 on 2026-05-21 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('TF', 'transfer')], default='TF', max_length=2)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('operation_date', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.accountmodel')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='account.accountmodel')),
            ],
        ),
    ]
