# Generated by Django 6.0.5 on 2026-06-24 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('TF', 'transfer')], default='TF', max_length=2)),
                ('value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('refund', models.BooleanField(default=False)),
                ('operation_date', models.DateTimeField(auto_now_add=True)),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.account')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer', to='account.account')),
            ],
        ),
    ]
