# Generated by Django 6.0.5 on 2026-05-22 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transactionmodel_recipient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='recipient',
            new_name='payee',
        ),
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='sender',
            new_name='payer',
        ),
        migrations.RenameField(
            model_name='transactionmodel',
            old_name='amount',
            new_name='value',
        ),
    ]
