# Generated by Django 6.0.5 on 2026-05-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_rename_recipient_transactionmodel_payee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='credit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transactionmodel',
            name='debit',
            field=models.BooleanField(default=False),
        ),
    ]
