# Generated by Django 6.0.5 on 2026-05-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_transactionmodel_credit_transactionmodel_debit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='credit',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='debit',
            field=models.BooleanField(),
        ),
    ]
