# Generated by Django 6.0.5 on 2026-05-25 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_transactionmodel_credit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionmodel',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='transactionmodel',
            name='debit',
        ),
    ]
