# Generated by Django 6.0.5 on 2026-05-25 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_remove_transactionmodel_credit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionmodel',
            name='refund',
            field=models.BooleanField(default=False),
        ),
    ]
