from django.shortcuts import get_object_or_404
from drf_spectacular.utils import OpenApiExample, OpenApiResponse, extend_schema
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import CreateModelMixin, ListModelMixin
from rest_framework.permissions import IsAuthenticated
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from account.models import Account
from account.serializers import AccountCreationSerializer, AccountResponseSerializer
from user.permissions import ENV_PERMISSION_CLASS


# Create your views here.
class AccountViewSet(CreateModelMixin, ListModelMixin, GenericViewSet):
    serializer_class = AccountResponseSerializer

    def get_permissions(self):
        self.permission_classes = [IsAuthenticated]
        if self.action == "list":
            self.permission_classes = [ENV_PERMISSION_CLASS]
        return super().get_permissions()

    @extend_schema(
        summary="Retrieve authenticated user's account",
        description="Returns the account information associated with the authenticated user.",
        tags=["Accounts"],
        responses={
            200: AccountResponseSerializer,
            403: OpenApiResponse(description="Not authenticated"),
            404: OpenApiResponse(description="Account not found for the authenticated user"),
        },
        examples=[
            OpenApiExample(
                "Account response",
                summary="Example account response",
                value={
                    "client": "João Silva",
                    "email": "user@example.com",
                    "agency": "1002",
                    "number": "1000001",
                },
                response_only=True,
            ),
        ],
    )
    @action(detail=False, methods=["GET"])
    def me(self, request):
        account = get_object_or_404(Account, client=request.user)
        return Response(AccountResponseSerializer(account).data)

    @extend_schema(
        summary="Create a bank account to authenticated user",
        description=(
            "Creates a bank account for the authenticated user.\n\n"
            "The account is automatically generated by the system for demonstration purposes:\n"
            "- A 7-digit account number is generated\n"
            "- A random initial balance between 2000 and 10000 is assigned\n"
            "- The agency is set to a fixed value (1002)\n\n"
            "Only one account is allowed per user."
        ),
        tags=["Accounts"],
        request=None,
        responses={
            201: AccountResponseSerializer,
            400: OpenApiResponse(description="Validation error - customer already has an active account"),
            403: OpenApiResponse(description="Not authenticated"),
        },
        examples=[
            OpenApiExample(
                "Empty body",
                summary="Example account creation request",
                description="The request body is empty; the account is auto-generated.",
                value={},
                request_only=True,
            ),
            OpenApiExample(
                "Account created response",
                summary="Example account creation response",
                value={
                    "client": "João Silva",
                    "email": "user@example.com",
                    "agency": "1002",
                    "number": "1234567",
                },
                response_only=True,
            ),
        ],
    )
    def create(self, request):
        serializer = AccountCreationSerializer(
            data=request.data, context={"user": request.user}
        )
        serializer.is_valid(raise_exception=True)
        account = serializer.save()

        return Response(
            AccountResponseSerializer(account).data,
            status=status.HTTP_201_CREATED,
        )

    @extend_schema(
        summary="List all registered accounts",
        description=(
            "Returns a list of all registered accounts.\n\n"
            "Access to this endpoint depends on the project's environment:\n"
            "- Development and testing: available to authenticated users according to the configured permissions.\n"
            "- Production: restricted to the superuser."
        ),
        tags=["Accounts"],
        responses={
            200: AccountResponseSerializer(many=True),
            403: OpenApiResponse(description="Access denied in production environment"),
        },
        examples=[
            OpenApiExample(
                "Account list response",
                summary="Example account list response",
                value=[
                    {
                        "client": "João Silva",
                        "email": "user@example.com",
                        "agency": "1002",
                        "number": "1000001",
                    },
                ],
                response_only=True,
            ),
        ],
    )
    def list(self, request, *args, **kwargs):
        accounts = Account.objects.all().order_by("-created_at")
        return Response(
            AccountResponseSerializer(accounts, many=True).data,
            status=status.HTTP_200_OK,
        )
