# Generated by Django 6.0.5 on 2026-06-29 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='user_model',
            new_name='user',
        ),
    ]
