# Generated by Django 6.0.5 on 2026-06-24 19:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('client_type', models.CharField(blank=True, choices=[('business', 'business'), ('person', 'person')], max_length=8, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_superuser', True), ('client_type__isnull', True)), models.Q(('is_superuser', False), ('client_type__isnull', False)), _connector='OR'), name='superuser_or_client')],
            },
        ),
    ]
